Complete all challenges

diff --git a/generate-credentials/check-vault b/generate-credentials/check-vault
--- a/generate-credentials/check-vault
+++ b/generate-credentials/check-vault
@@ -1,15 +1,8 @@
-#!/bin/sh
-#
-# This is a sample check script. Rename this file to check-$CONTAINER
-# (where $container is the name of the container as defined in your config.yml),
-# and replace this content with your own script.
-#
-# This script will be run when you check the challenge.
-#
-# Remember that the exit code is important. See the documentation
-# for more information.
-#
-
-echo "This is the check script"
+#!/bin/bash
+CREDENTIALS=$(curl -s -H "X-Vault-Token: $(cat /root/.vault-token)" http://localhost:8200/v1/database/creds/postgres | jq .data)
+if [ "$CREDENTIALS" == "null" ]; then
+  fail-message "Could not request credentials from the creds/postgres endpoint"
+  exit 1
+fi
 
 exit 0
